"""LexlingSetup.exe - installs, updates and uninstalls the game (called WordGuess until 0.18.0).

Built by scripts/build.ps1. Ported from the Reckless Driving installer (itself modelled on Lockdown's,
minus the service / watchdog / admin parts a game does not need): it installs per-user into
%LOCALAPPDATA%\\Programs and never shows a UAC prompt.

Install vs update is not a separate build or a switch the player picks: the same exe reads
DisplayVersion from the uninstall key, and if the game is already there the wording and the button
change to Update. Shipping an update therefore means shipping one new exe.

Your saves live in %LOCALAPPDATA%\\Lexling (WebView2's profile, holding the game's localStorage:
settings, saved games, statistics, badges). That folder is deliberately OUTSIDE the program folder,
which is the only thing an update replaces - so updating cannot cost you anything. It is removed only
if you tick the box while uninstalling.

THE RENAME. Up to 0.17.2 the game was WordGuess: its own program folder, shortcuts, uninstall entry
and saves folder, all under that name. A Lexling install that finds them treats itself as the update
it is: it retires the old program (folder, shortcuts, uninstall entry) and moves the saves folder to
its new name, whole. The web page's origin (the local port) did not change, so the saves inside it
are read exactly as before.
"""
import ctypes
import os
import shutil
import subprocess
import sys
import threading
import time
import tkinter as tk
import winreg
import zipfile
from pathlib import Path
from tkinter import messagebox, ttk

from version import VERSION   # (generated by scripts/build.ps1 from app/js/version.js)

APP = "Lexling"
EXE_NAME = "Lexling.exe"
FOLDER = "Lexling"
ICON = "lexling.ico"
OLD_APP = "WordGuess"            # the name until 0.18.0 - see THE RENAME above
KEEPS = "saved games, statistics and badges"
INSTALL_DIR = Path(os.environ.get("LOCALAPPDATA", Path.home())) / "Programs" / FOLDER
SAVE_DIR = Path(os.environ.get("LOCALAPPDATA", Path.home())) / FOLDER
UNINSTALL_KEY = rf"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FOLDER}"
START_MENU = Path(os.environ.get("APPDATA", Path.home())) / r"Microsoft\Windows\Start Menu\Programs"
DESKTOP = Path(os.environ.get("USERPROFILE", Path.home())) / "Desktop"
SHORTCUT = f"{APP}.lnk"
OLD_INSTALL_DIR = INSTALL_DIR.parent / OLD_APP
OLD_SAVE_DIR = SAVE_DIR.parent / OLD_APP
OLD_UNINSTALL_KEY = rf"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{OLD_APP}"
NEWLINE = chr(10)
NO_WINDOW = subprocess.CREATE_NO_WINDOW
SYSTEM32 = Path(os.environ.get("SystemRoot", r"C:\Windows")) / "System32"
# Full paths: a user's PATH is not guaranteed to include System32 (it didn't on one of the machines
# the Lockdown installer ran on).
TOOLS = {"taskkill": SYSTEM32 / "taskkill.exe",
         "powershell": SYSTEM32 / r"WindowsPowerShell\v1.0\powershell.exe",
         "cmd": SYSTEM32 / "cmd.exe",
         "explorer.exe": Path(os.environ.get("SystemRoot", r"C:\Windows")) / "explorer.exe"}


def tool(name: str) -> str:
    return str(TOOLS.get(name, name))


def run(*args) -> subprocess.CompletedProcess:
    return subprocess.run([tool(args[0]), *args[1:]], capture_output=True, text=True,
                          creationflags=NO_WINDOW)


def payload() -> Path:
    return Path(getattr(sys, "_MEIPASS", Path(__file__).parent)) / "payload.zip"


def installed_version(key_path: str = UNINSTALL_KEY) -> str | None:
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path) as key:
            return winreg.QueryValueEx(key, "DisplayVersion")[0]
    except OSError:
        return None


def old_version() -> str | None:
    """The version of a WordGuess install this one takes over from (THE RENAME), if there is one."""
    return installed_version(OLD_UNINSTALL_KEY)


# ---------- steps ----------

def stop_game(log):
    log("Closing the game if it's running...")
    run("taskkill", "/F", "/IM", EXE_NAME)
    run("taskkill", "/F", "/IM", f"{OLD_APP}.exe")


def retire_old(log):
    """THE RENAME: take over from a WordGuess install. Its saves move to the new name, whole; its
    program folder, shortcuts and uninstall entry go. The saves come first and are never deleted."""
    if OLD_SAVE_DIR.is_dir() and not SAVE_DIR.exists():
        log(f"Moving your {KEEPS} to the new name...")
        # WebView2's helper processes can hold the folder for a moment after the game is closed
        for _ in range(20):
            try:
                OLD_SAVE_DIR.rename(SAVE_DIR)
                break
            except OSError:
                time.sleep(0.5)
        else:
            log(f"(They are still in {OLD_SAVE_DIR} - the game moves them on its first start.)")
    if OLD_INSTALL_DIR.exists() or old_version():
        log(f"Removing the old {OLD_APP} program...")
        shutil.rmtree(OLD_INSTALL_DIR, ignore_errors=True)
        for folder in (START_MENU, DESKTOP):
            (folder / f"{OLD_APP}.lnk").unlink(missing_ok=True)
        try:
            winreg.DeleteKey(winreg.HKEY_CURRENT_USER, OLD_UNINSTALL_KEY)
        except OSError:
            pass


def copy_files(log):
    log("Copying the game...")
    INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    internal = INSTALL_DIR / "_internal"
    if internal.exists():      # the previous version's libraries AND app files - replace them wholesale
        shutil.rmtree(internal, ignore_errors=True)
    with zipfile.ZipFile(payload()) as z:
        z.extractall(INSTALL_DIR)
    uninstaller = INSTALL_DIR / f"Uninstall {APP}.exe"
    if getattr(sys, "frozen", False) and Path(sys.executable).resolve() != uninstaller.resolve():
        shutil.copy2(sys.executable, uninstaller)


def shortcuts(log):
    log("Adding shortcuts...")
    target = INSTALL_DIR / EXE_NAME
    for folder in (START_MENU, DESKTOP):
        link = folder / SHORTCUT
        # A shortcut that already exists keeps the icon Explorer cached for it, so an update that
        # changes the app icon leaves the old one on the desktop (the taskbar, which reads the running
        # exe, shows the new one - which is exactly how it looks wrong). Rewriting the file is not
        # enough; the cache is keyed to the path. Remove it, write it again, then tell the shell.
        link.unlink(missing_ok=True)
        run("powershell", "-NoProfile", "-Command",
            f"$s = (New-Object -ComObject WScript.Shell).CreateShortcut('{link}'); "
            f"$s.TargetPath = '{target}'; $s.WorkingDirectory = '{INSTALL_DIR}'; "
            f"$s.IconLocation = '{target},0'; $s.Description = '{APP}'; $s.Save()")
    refresh_icons()


def refresh_icons():
    """Ask Explorer to re-read icons (SHCNE_ASSOCCHANGED), instead of waiting for its cache to age out."""
    try:
        ctypes.windll.shell32.SHChangeNotify(0x08000000, 0x0000, None, None)
    except Exception:
        pass                                   # cosmetic: never fail an install over it


def uninstall_entry(log):
    size_kb = sum(f.stat().st_size for f in INSTALL_DIR.rglob("*") if f.is_file()) // 1024
    with winreg.CreateKeyEx(winreg.HKEY_CURRENT_USER, UNINSTALL_KEY, 0, winreg.KEY_WRITE) as key:
        for name, value in {
            "DisplayName": APP,
            "DisplayVersion": VERSION,
            "Publisher": APP,
            "DisplayIcon": str(INSTALL_DIR / EXE_NAME),
            "InstallLocation": str(INSTALL_DIR),
            "UninstallString": f'"{INSTALL_DIR / f"Uninstall {APP}.exe"}" --uninstall',
        }.items():
            winreg.SetValueEx(key, name, 0, winreg.REG_SZ, value)
        for name, value in {"NoModify": 1, "NoRepair": 1, "EstimatedSize": size_kb}.items():
            winreg.SetValueEx(key, name, 0, winreg.REG_DWORD, value)


def install(log):
    stop_game(log)
    retire_old(log)
    copy_files(log)
    shortcuts(log)
    uninstall_entry(log)
    log(f"{APP} {VERSION} is installed.")


def uninstall(log, delete_saves: bool):
    stop_game(log)
    log("Removing shortcuts...")
    for folder in (START_MENU, DESKTOP):
        (folder / SHORTCUT).unlink(missing_ok=True)
    try:
        winreg.DeleteKey(winreg.HKEY_CURRENT_USER, UNINSTALL_KEY)
    except OSError:
        pass
    if delete_saves:
        log(f"Deleting your {KEEPS}...")
        shutil.rmtree(SAVE_DIR, ignore_errors=True)
    else:
        log("Your saves are kept - reinstalling will pick them up again.")
    log(f"{APP} is uninstalled. The game folder goes when you close this window.")


def remove_program_folder():
    """The uninstaller runs FROM the program folder, so delete it a moment after we quit."""
    subprocess.Popen(
        f'"{tool("cmd")}" /c "{SYSTEM32 / "PING.EXE"}" 127.0.0.1 -n 3 >nul & rmdir /s /q "{INSTALL_DIR}"',
        creationflags=NO_WINDOW)


def launch_game():
    subprocess.Popen([tool("explorer.exe"), str(INSTALL_DIR / EXE_NAME)], creationflags=NO_WINDOW)


# ---------- window ----------

class SetupWindow(tk.Tk):
    def __init__(self, uninstalling: bool):
        super().__init__()
        self.uninstalling = uninstalling
        self.title(f"Uninstall {APP}" if uninstalling else f"{APP} Setup")
        self.geometry("520x340")
        self.resizable(False, False)
        icon = Path(getattr(sys, "_MEIPASS", ".")) / ICON
        if icon.exists():
            self.iconbitmap(str(icon))
        box = ttk.Frame(self, padding=18)
        box.pack(fill="both", expand=True)

        current = installed_version()
        renamed = None if current else old_version()     # a WordGuess install this one replaces
        if uninstalling:
            intro = (f"This removes {APP} from your PC.\n"
                     f"Your {KEEPS} are kept unless you tick the box.")
        elif current == VERSION:
            intro = (f"{APP} {VERSION} is already installed.\n"
                     "Re-installing it will not affect your saves.")
        elif current:
            intro = (f"{APP} {current} is installed. This updates it to {VERSION}.\n"
                     f"Your {KEEPS} are kept.")
        elif renamed:
            intro = (f"{OLD_APP} {renamed} is installed. This updates it to {VERSION} under its new "
                     f"name, {APP}.\nYour {KEEPS} are kept.")
        else:
            intro = (f"This installs {APP} {VERSION} for your account only.\n"
                     f"No administrator rights needed. It goes in {INSTALL_DIR}.")
        ttk.Label(box, text=intro, wraplength=470, justify="left").pack(anchor="w")

        self.delete_saves = tk.BooleanVar(value=False)
        if uninstalling:
            ttk.Checkbutton(box, text=f"Also delete my {KEEPS}",
                            variable=self.delete_saves).pack(anchor="w", pady=(10, 0))

        self.log_box = tk.Text(box, height=8, width=60, state="disabled", relief="flat",
                               background="#F2F2F2", font=("Segoe UI", 9))
        self.log_box.pack(fill="both", expand=True, pady=12)

        self.run_app = tk.BooleanVar(value=True)
        self.done_note = ttk.Label(box, text="", foreground="#1E7A46", font=("Segoe UI", 9, "bold"))
        self.run_check = ttk.Checkbutton(box, text=f"Play {APP} now", variable=self.run_app)
        self.buttons = ttk.Frame(box)
        self.buttons.pack(fill="x")
        label = "Uninstall" if uninstalling else ("Re-install" if current == VERSION
                                                  else "Update" if current or renamed else "Install")
        self.go = ttk.Button(self.buttons, text=label, command=self._start)
        self.go.pack(side="right")
        self.close = ttk.Button(self.buttons, text="Cancel", command=self._close)
        self.close.pack(side="right", padx=8)
        self.protocol("WM_DELETE_WINDOW", self._close)
        self.done = False

    def log(self, text: str):
        self.after(0, self._append, text)

    def _append(self, text: str):
        self.log_box.configure(state="normal")
        self.log_box.insert("end", text + "\n")
        self.log_box.see("end")
        self.log_box.configure(state="disabled")

    def _start(self):
        # Re-installing the SAME version is almost always an accident (an installer kept from a
        # previous update, a second double-click), so confirm it outright. Checked at click time,
        # since the install may have changed while this window sat open.
        if not self.uninstalling and installed_version() == VERSION:
            if not messagebox.askyesno(
                    f"{APP} {VERSION} is already installed",
                    f"You already have {APP} {VERSION} - this is the same version, not an "
                    f"update." + NEWLINE + NEWLINE +
                    f"Installing it again is harmless and keeps your {KEEPS}. Do it anyway?",
                    parent=self, default="no"):
                return
        self.go.configure(state="disabled")
        self.close.configure(state="disabled")
        threading.Thread(target=self._work, daemon=True).start()

    def _work(self):
        try:
            if self.uninstalling:
                uninstall(self.log, self.delete_saves.get())
                self.done = True
                self.after(0, lambda: self.close.configure(state="normal", text="Close"))
            else:
                install(self.log)
                self.done = True
                self.after(0, self._finish_install)
        except Exception as e:      # show it rather than vanish
            self.log(f"Something went wrong: {e}")
            self.after(0, lambda: self.close.configure(state="normal", text="Close"))

    def _finish_install(self):
        self.go.pack_forget()
        self.done_note.configure(text=f"\u2713  {APP} {VERSION} is ready.")
        self.done_note.pack(anchor="w", pady=(0, 2), before=self.buttons)
        self.run_check.pack(anchor="w", pady=(0, 8), before=self.buttons)
        self.close.configure(state="normal", text="Finish")

    def _close(self):
        if str(self.close.cget("state")) == "disabled":   # busy: don't quit halfway
            return
        self.destroy()
        if self.uninstalling and self.done:
            remove_program_folder()
        elif not self.uninstalling and self.done and self.run_app.get():
            launch_game()


def main():
    SetupWindow("--uninstall" in sys.argv).mainloop()


if __name__ == "__main__":
    main()
